export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice: number;
  category: string;
  collection: string;
  rating: number;
  reviews: number;
  sold: number;
  description: string;
  features: string[];
  image: string;
  badge?: string;
  inStock: boolean;
}

export interface Collection {
  id: string;
  name: string;
  description: string;
  image: string;
  productCount: number;
}

export const collections: Collection[] = [
  {
    id: "best-sellers",
    name: "Best Sellers",
    description: "Our most-loved products — chosen by thousands of happy customers",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    productCount: 12,
  },
  {
    id: "facial-devices",
    name: "Facial Devices",
    description: "Clinic-quality skin treatments at home",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    productCount: 9,
  },
  {
    id: "body-care",
    name: "Body Care Devices",
    description: "Professional body treatments & massage tools",
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800&q=80",
    productCount: 5,
  },
  {
    id: "oral-care",
    name: "Oral & Dental Care",
    description: "Dentist-approved tools for a perfect smile",
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800&q=80",
    productCount: 4,
  },
  {
    id: "hair-care",
    name: "Hair Care Devices",
    description: "Salon-quality hair tools for every style",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    productCount: 4,
  },
  {
    id: "hygiene-kits",
    name: "Hygiene Care Packages",
    description: "Complete self-care bundles for daily routines",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80",
    productCount: 6,
  },
  {
    id: "nail-care",
    name: "Nail Care",
    description: "Professional nail tools & salon kits",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80",
    productCount: 3,
  },
];

export const products: Product[] = [
  // ── Facial Devices ────────────────────────────────────────────────────
  {
    id: "1",
    slug: "led-light-therapy-mask",
    name: "7-Color LED Light Therapy Face Mask",
    price: 49.99,
    originalPrice: 129.99,
    category: "LED Therapy",
    collection: "facial-devices",
    rating: 4.8,
    reviews: 18423,
    sold: 86000,
    description:
      "Professional 7-color LED light therapy mask with red, blue, green, and infrared modes. Targets acne, wrinkles, hyperpigmentation, and dullness. Hands-free design with USB power.",
    features: [
      "7 LED wavelengths",
      "Red (anti-aging), Blue (acne), Green (brightening)",
      "Hands-free design",
      "20-minute auto shut-off",
      "Dermatologist tested",
    ],
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "2",
    slug: "microcurrent-facial-toning",
    name: "Microcurrent Facial Toning Device",
    price: 59.99,
    originalPrice: 149.99,
    category: "Microcurrent",
    collection: "facial-devices",
    rating: 4.7,
    reviews: 12304,
    sold: 54000,
    description:
      "FDA-cleared microcurrent device lifts and tones facial muscles, reduces fine lines, and firms skin in 5 minutes a day. Includes conductive gel.",
    features: [
      "FDA-cleared technology",
      "5-minute daily treatment",
      "Lifts & firms skin",
      "Conductive gel included",
      "Rechargeable battery",
    ],
    image: "https://images.unsplash.com/photo-1583241475880-083f84372725?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
  },
  {
    id: "3",
    slug: "ice-roller-face",
    name: "Ice Roller for Face & Eyes",
    price: 18.99,
    originalPrice: 39.99,
    category: "Facial Roller",
    collection: "facial-devices",
    rating: 4.9,
    reviews: 31042,
    sold: 143000,
    description:
      "Stainless steel ice roller shrinks pores, reduces puffiness, and soothes redness instantly. Freeze-and-roll design stays cold for 15+ minutes.",
    features: [
      "Stainless steel head",
      "Stays cold 15+ minutes",
      "Reduces puffiness fast",
      "Shrinks pores",
      "Migraine & headache relief",
    ],
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },
  {
    id: "4",
    slug: "rose-quartz-gua-sha-set",
    name: "Rose Quartz Facial Roller & Gua Sha Set",
    price: 14.99,
    originalPrice: 34.99,
    category: "Facial Roller",
    collection: "facial-devices",
    rating: 4.8,
    reviews: 26034,
    sold: 121000,
    description:
      "Authentic rose quartz facial roller and gua sha tool. Reduces puffiness, stimulates lymphatic drainage, and boosts serum absorption. Comes in velvet gift bag.",
    features: [
      "Authentic rose quartz",
      "Dual-end roller",
      "Gua sha board included",
      "Reduces puffiness",
      "Velvet gift bag",
    ],
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "5",
    slug: "dermaplaning-tool",
    name: "Dermaplaning Facial Exfoliator (4-Pack)",
    price: 16.99,
    originalPrice: 34.99,
    category: "Exfoliation",
    collection: "facial-devices",
    rating: 4.7,
    reviews: 19203,
    sold: 88000,
    description:
      "Professional-grade dermaplaning tool removes peach fuzz, dead skin, and unclogs pores. Reveals instantly smoother, brighter skin. Includes 4 replacement heads.",
    features: [
      "4 precision blades",
      "Removes peach fuzz",
      "Ergonomic handle",
      "Safe for all skin types",
      "Dermatologist approved",
    ],
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80",
    badge: "Trending",
    inStock: true,
  },
  {
    id: "6",
    slug: "ultrasonic-skin-scrubber",
    name: "Ultrasonic Skin Scrubber Spatula",
    price: 34.99,
    originalPrice: 79.99,
    category: "Deep Cleansing",
    collection: "facial-devices",
    rating: 4.6,
    reviews: 8921,
    sold: 37000,
    description:
      "28,000Hz ultrasonic vibrations deep-cleanse pores, remove blackheads, and infuse serums into skin. 4 modes: Cleanse, Lift, Exfoliate, Hydrate.",
    features: [
      "28,000 Hz vibrations",
      "4 treatment modes",
      "Blackhead removal",
      "Serum infusion mode",
      "USB rechargeable",
    ],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    inStock: true,
  },

  // ── Body Care Devices ────────────────────────────────────────────────
  {
    id: "7",
    slug: "electric-body-massager",
    name: "Percussion Body Massager Gun",
    price: 54.99,
    originalPrice: 129.99,
    category: "Massage",
    collection: "body-care",
    rating: 4.8,
    reviews: 22041,
    sold: 98000,
    description:
      "6-speed deep tissue percussion massager with 6 interchangeable heads. Relieves muscle soreness, improves circulation. Ultra-quiet 40dB motor.",
    features: [
      "6 speed levels",
      "6 massage heads",
      "Ultra-quiet 40dB",
      "2400mAh battery (6hr)",
      "Carrying case included",
    ],
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "8",
    slug: "dry-body-brush-set",
    name: "Dry Body Brushing Set",
    price: 19.99,
    originalPrice: 39.99,
    category: "Exfoliation",
    collection: "body-care",
    rating: 4.8,
    reviews: 14302,
    sold: 63000,
    description:
      "Natural sisal dry body brush set with long handle and face brush. Exfoliates skin, boosts circulation, and reduces appearance of cellulite.",
    features: [
      "Natural sisal bristles",
      "Detachable long handle",
      "Face brush included",
      "Reduces cellulite",
      "Stimulates lymphatic drainage",
    ],
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
  },
  {
    id: "9",
    slug: "cellulite-cupping-set",
    name: "Silicone Cupping Massage Set (4-Pack)",
    price: 14.99,
    originalPrice: 29.99,
    category: "Cupping",
    collection: "body-care",
    rating: 4.7,
    reviews: 9823,
    sold: 42000,
    description:
      "Soft silicone cups for facial and body cupping massage. Increases circulation, reduces muscle tension, and minimizes cellulite. 4 sizes included.",
    features: [
      "4 cup sizes",
      "Medical-grade silicone",
      "Face & body use",
      "Reduces cellulite",
      "Reusable & easy clean",
    ],
    image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=600&q=80",
    badge: "Trending",
    inStock: true,
  },
  {
    id: "10",
    slug: "electric-pumice-foot-file",
    name: "Electric Callus Remover & Foot Spa Kit",
    price: 29.99,
    originalPrice: 64.99,
    category: "Foot Care",
    collection: "body-care",
    rating: 4.9,
    reviews: 27831,
    sold: 127000,
    description:
      "Rechargeable electric foot file with 3 roller heads removes calluses and cracked heels in minutes. IPX6 waterproof — use in shower.",
    features: [
      "3 interchangeable rollers",
      "IPX6 waterproof",
      "Use wet or dry",
      "Rechargeable USB-C",
      "2-speed settings",
    ],
    image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },
  {
    id: "11",
    slug: "body-sculpting-massager",
    name: "EMS Body Sculpting Toning Device",
    price: 44.99,
    originalPrice: 99.99,
    category: "Body Toning",
    collection: "body-care",
    rating: 4.6,
    reviews: 7312,
    sold: 29000,
    description:
      "EMS (Electrical Muscle Stimulation) toning pads firm and tone abs, arms, and thighs. 6 modes, 10 intensities. Wear while relaxing.",
    features: [
      "EMS technology",
      "6 training modes",
      "10 intensity levels",
      "Wireless remote",
      "Rechargeable pads",
    ],
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80",
    inStock: true,
  },

  // ── Oral & Dental Care ────────────────────────────────────────────────
  {
    id: "12",
    slug: "water-flosser",
    name: "Cordless Water Flosser",
    price: 34.99,
    originalPrice: 74.99,
    category: "Oral Care",
    collection: "oral-care",
    rating: 4.8,
    reviews: 19841,
    sold: 91000,
    description:
      "Cordless water flosser with 3 pressure modes and 4 nozzle tips. Removes 99.9% of plaque. Waterproof IPX7 — use in shower. 30-day battery life.",
    features: [
      "3 pressure modes",
      "4 nozzle tips",
      "IPX7 waterproof",
      "30-day battery",
      "Removes 99.9% plaque",
    ],
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "13",
    slug: "teeth-whitening-kit",
    name: "LED Teeth Whitening Kit",
    price: 26.99,
    originalPrice: 59.99,
    category: "Whitening",
    collection: "oral-care",
    rating: 4.7,
    reviews: 24093,
    sold: 109000,
    description:
      "Professional-grade LED whitening kit with 3 whitening gel syringes. Removes stains from coffee, wine, and tobacco. Results in 7 days.",
    features: [
      "LED accelerator light",
      "3 whitening gel syringes",
      "Sensitivity-free formula",
      "Results in 7 days",
      "Enamel safe",
    ],
    image: "https://images.unsplash.com/photo-1559591937-abc77a68a8ba?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },
  {
    id: "14",
    slug: "tongue-scraper-set",
    name: "Stainless Steel Tongue Scraper (3-Pack)",
    price: 9.99,
    originalPrice: 19.99,
    category: "Oral Hygiene",
    collection: "oral-care",
    rating: 4.9,
    reviews: 33012,
    sold: 154000,
    description:
      "Medical-grade stainless steel tongue scrapers eliminate bad breath at the source. Reusable, rust-proof, and dishwasher safe. 3-pack.",
    features: [
      "Medical-grade steel",
      "3-pack value set",
      "Eliminates bad breath",
      "Dishwasher safe",
      "Eco-friendly & reusable",
    ],
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
  },
  {
    id: "15",
    slug: "smart-electric-toothbrush",
    name: "Sonic Electric Toothbrush with 5 Heads",
    price: 39.99,
    originalPrice: 89.99,
    category: "Toothbrush",
    collection: "oral-care",
    rating: 4.8,
    reviews: 16203,
    sold: 72000,
    description:
      "40,000 strokes/min sonic toothbrush with 5 brush heads, 5 cleaning modes, and 2-minute smart timer. 30-day USB charge.",
    features: [
      "40,000 strokes/min",
      "5 cleaning modes",
      "2-min smart timer",
      "5 brush heads included",
      "30-day battery life",
    ],
    image: "https://images.unsplash.com/photo-1559590564-542f80b4e3d0?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },

  // ── Hair Care Devices ────────────────────────────────────────────────
  {
    id: "16",
    slug: "hair-growth-laser-cap",
    name: "Scalp Massager & Hair Growth Serum Set",
    price: 22.99,
    originalPrice: 49.99,
    category: "Hair Growth",
    collection: "hair-care",
    rating: 4.7,
    reviews: 11203,
    sold: 49000,
    description:
      "Electric scalp massager stimulates follicles and promotes hair growth when used with included biotin serum. USB rechargeable, waterproof.",
    features: [
      "Electric scalp massage",
      "Biotin serum included",
      "IPX7 waterproof",
      "USB rechargeable",
      "For thinning hair",
    ],
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=80",
    badge: "Trending",
    inStock: true,
  },
  {
    id: "17",
    slug: "ionic-hair-dryer",
    name: "Professional Ionic Hair Dryer 1875W",
    price: 44.99,
    originalPrice: 99.99,
    category: "Hair Dryer",
    collection: "hair-care",
    rating: 4.8,
    reviews: 20931,
    sold: 94000,
    description:
      "1875W ionic hair dryer with 3 heat + 2 speed settings, cool shot button, and concentrator nozzle. Cuts drying time by 50% and eliminates frizz.",
    features: [
      "1875W powerful motor",
      "Ionic technology",
      "3 heat / 2 speed",
      "Cool shot button",
      "Concentrator nozzle",
    ],
    image: "https://images.unsplash.com/photo-1522337994170-5c60c7b63f56?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "18",
    slug: "automatic-hair-curler",
    name: "Automatic Rotating Hair Curler",
    price: 49.99,
    originalPrice: 109.99,
    category: "Curling",
    collection: "hair-care",
    rating: 4.6,
    reviews: 9312,
    sold: 41000,
    description:
      "Auto-rotating ceramic curling iron creates perfect curls in 10 seconds. 5 temperature settings, dual direction, and auto shut-off.",
    features: [
      "Auto-rotating barrel",
      "5 temperature settings",
      "Dual curl direction",
      "Ceramic coating",
      "Auto shut-off safety",
    ],
    image: "https://images.unsplash.com/photo-1560869713-da86a9ec5a44?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
  },
  {
    id: "19",
    slug: "satin-sleep-bonnet",
    name: "Satin Sleep Bonnet & Pillowcase Set",
    price: 21.99,
    originalPrice: 44.99,
    category: "Hair Protection",
    collection: "hair-care",
    rating: 4.9,
    reviews: 28031,
    sold: 131000,
    description:
      "Satin sleep bonnet + pillowcase set reduces friction, prevents breakage and frizz, and preserves hairstyles overnight. Adjustable elastic.",
    features: [
      "22-momme satin fabric",
      "Pillowcase included",
      "Adjustable elastic band",
      "Reduces frizz & breakage",
      "Multiple colors",
    ],
    image: "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },

  // ── Hygiene Care Packages ────────────────────────────────────────────
  {
    id: "20",
    slug: "complete-skincare-routine-kit",
    name: "Complete AM/PM Skincare Routine Kit",
    price: 59.99,
    originalPrice: 129.99,
    category: "Skincare Bundle",
    collection: "hygiene-kits",
    rating: 4.9,
    reviews: 14203,
    sold: 62000,
    description:
      "12-piece skincare routine set: cleanser, toner, vitamin C serum, retinol serum, hyaluronic acid, eye cream, day moisturizer, night cream, SPF30, face mask, sheet masks (3), and jade roller.",
    features: [
      "12 full-size products",
      "Complete AM & PM routine",
      "Vitamin C + Retinol serums",
      "Jade roller included",
      "All skin types",
    ],
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "21",
    slug: "luxury-bath-spa-kit",
    name: "Luxury Bath & Spa Gift Set",
    price: 39.99,
    originalPrice: 79.99,
    category: "Bath Bundle",
    collection: "hygiene-kits",
    rating: 4.8,
    reviews: 18432,
    sold: 83000,
    description:
      "10-piece spa bath set: bath bombs (6), body scrub, bath salts, bath pillow, loofah sponge, and aromatherapy candle. Perfect gift set.",
    features: [
      "10-piece gift set",
      "6 bath bombs",
      "Aromatherapy candle",
      "Body scrub & bath salts",
      "Gift-ready packaging",
    ],
    image: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
  },
  {
    id: "22",
    slug: "mens-grooming-kit",
    name: "Men's Complete Grooming Kit",
    price: 44.99,
    originalPrice: 94.99,
    category: "Grooming Bundle",
    collection: "hygiene-kits",
    rating: 4.7,
    reviews: 12904,
    sold: 57000,
    description:
      "8-piece premium grooming kit: face wash, moisturizer, shave gel, aftershave balm, beard oil, beard comb, lip balm, and eye cream. All-natural ingredients.",
    features: [
      "8 full-size products",
      "Beard care included",
      "All-natural formula",
      "Fragrance-free options",
      "Gift-box packaging",
    ],
    image: "https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "23",
    slug: "acne-blemish-kit",
    name: "Acne & Blemish Control Complete Kit",
    price: 32.99,
    originalPrice: 69.99,
    category: "Acne Care",
    collection: "hygiene-kits",
    rating: 4.8,
    reviews: 21034,
    sold: 96000,
    description:
      "Complete acne-fighting kit: salicylic cleanser, niacinamide toner, benzoyl peroxide spot treatment, oil-free moisturizer, and 108 hydrocolloid patches.",
    features: [
      "5-step routine",
      "108 hydrocolloid patches",
      "Salicylic acid & BHA",
      "Oil-free formulas",
      "Dermatologist developed",
    ],
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },
  {
    id: "24",
    slug: "self-care-subscription-box",
    name: "Self-Care Essentials Box (Monthly Kit)",
    price: 27.99,
    originalPrice: 54.99,
    category: "Self-Care Bundle",
    collection: "hygiene-kits",
    rating: 4.9,
    reviews: 9823,
    sold: 44000,
    description:
      "Monthly self-care box with curated essentials: face mask, lip treatment, hand cream, body mist, eye patches, and a beauty tool. Changes monthly.",
    features: [
      "6 curated products",
      "New themes monthly",
      "Full-size products only",
      "Travel-friendly sizes",
      "Gift-ready box",
    ],
    image: "https://images.unsplash.com/photo-1522337994170-5c60c7b63f56?w=600&q=80",
    badge: "Trending",
    inStock: true,
  },

  // ── New High-Converters ───────────────────────────────────────────────
  {
    id: "28",
    slug: "red-light-therapy-wand",
    name: "Red Light Therapy Wand — Anti-Aging",
    price: 39.99,
    originalPrice: 94.99,
    category: "Red Light Therapy",
    collection: "facial-devices",
    rating: 4.8,
    reviews: 14821,
    sold: 67000,
    description:
      "Handheld 630nm + 850nm dual-wavelength red light therapy wand reduces fine lines, boosts collagen, and fades dark spots in 10-minute daily sessions.",
    features: [
      "630nm + 850nm dual wavelength",
      "Collagen-stimulating technology",
      "Fades dark spots & fine lines",
      "10-minute daily sessions",
      "USB-C rechargeable",
    ],
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600&q=80",
    badge: "Trending",
    inStock: true,
  },
  {
    id: "29",
    slug: "blackhead-vacuum-camera",
    name: "Blackhead Remover Vacuum with HD Camera",
    price: 32.99,
    originalPrice: 74.99,
    category: "Deep Cleansing",
    collection: "facial-devices",
    rating: 4.7,
    reviews: 22134,
    sold: 103000,
    description:
      "5-megapixel HD camera shows your pores live on your phone while 3-level suction safely extracts blackheads, whiteheads, and sebum plugs. 5 suction heads.",
    features: [
      "5MP HD pore camera",
      "WiFi app-connected",
      "3 suction strength levels",
      "5 interchangeable heads",
      "Safe for sensitive skin",
    ],
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "30",
    slug: "silicone-facial-cleansing-brush",
    name: "Sonic Silicone Facial Cleansing Brush",
    price: 13.99,
    originalPrice: 29.99,
    category: "Face Cleansing",
    collection: "facial-devices",
    rating: 4.9,
    reviews: 38902,
    sold: 178000,
    description:
      "7,000 micro-vibrations per minute remove makeup, oil, and dirt 10× better than hands. Ultra-soft medical-grade silicone — safe for all skin types. Waterproof.",
    features: [
      "7,000 vibrations/min",
      "Medical-grade silicone",
      "100% waterproof",
      "USB rechargeable",
      "Works with any cleanser",
    ],
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },
  {
    id: "31",
    slug: "blue-light-blocking-glasses-set",
    name: "Blue Light Blocking Glasses — 3-Pack",
    price: 19.99,
    originalPrice: 44.99,
    category: "Eye Wellness",
    collection: "hygiene-kits",
    rating: 4.8,
    reviews: 29841,
    sold: 138000,
    description:
      "Block 99% of blue light from screens to reduce eye strain, improve sleep quality, and prevent digital headaches. Anti-glare + UV400 coating. 3 styles included.",
    features: [
      "99% blue light blocking",
      "Anti-glare UV400 coating",
      "3 frame styles",
      "Reduces eye strain",
      "Improves sleep quality",
    ],
    image: "https://images.unsplash.com/photo-1483706571191-85c0c76b1947?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },

  // ── Nail Care ─────────────────────────────────────────────────────────
  {
    id: "25",
    slug: "electric-nail-drill-kit",
    name: "Professional Electric Nail Drill Kit",
    price: 26.99,
    originalPrice: 59.99,
    category: "Nail Drill",
    collection: "nail-care",
    rating: 4.7,
    reviews: 16892,
    sold: 77000,
    description:
      "35,000 RPM e-file nail drill with 11 carbide bits, dust collector, and UV lamp. Perfect for gel nails, acrylics, and natural nails.",
    features: [
      "35,000 RPM motor",
      "11 drill bits included",
      "Built-in dust collector",
      "USB rechargeable",
      "4-hour runtime",
    ],
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "26",
    slug: "gel-nail-uv-lamp",
    name: "48W UV/LED Gel Nail Lamp",
    price: 22.99,
    originalPrice: 49.99,
    category: "UV Lamp",
    collection: "nail-care",
    rating: 4.8,
    reviews: 23041,
    sold: 107000,
    description:
      "48W dual UV/LED lamp cures all gel polishes in 30–60 seconds. Smart sensor auto-detection, 3 timer modes, and pain-free cure technology.",
    features: [
      "48W dual UV/LED",
      "Cures in 30-60 seconds",
      "Smart sensor auto-on",
      "3 timer settings",
      "Pain-free technology",
    ],
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80",
    badge: "#1 Seller",
    inStock: true,
  },
  {
    id: "27",
    slug: "complete-nail-art-kit",
    name: "Complete Nail Art Starter Kit",
    price: 34.99,
    originalPrice: 74.99,
    category: "Nail Art",
    collection: "nail-care",
    rating: 4.6,
    reviews: 11023,
    sold: 49000,
    description:
      "87-piece nail art kit: 30 gel colors, base & top coat, nail drill, UV lamp, brush set, nail tips, and glitters. Everything to start gel nails at home.",
    features: [
      "87 pieces total",
      "30 gel color polishes",
      "UV lamp + nail drill",
      "Nail art brush set",
      "Beginner friendly",
    ],
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
  },
];

export function getProductsByCollection(collectionId: string): Product[] {
  if (collectionId === "best-sellers") return getBestSellers(12);
  return products.filter((p) => p.collection === collectionId);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.collection === product.collection && p.id !== product.id)
    .slice(0, limit);
}

export function getBestSellers(limit = 8): Product[] {
  return [...products].sort((a, b) => b.sold - a.sold).slice(0, limit);
}

export function getCollectionById(id: string): Collection | undefined {
  return collections.find((c) => c.id === id);
}
