export interface Product {
  id: string;
  slug: string;
  name: string;
  price: number;
  originalPrice: number;
  category: string;
  collection: string;
  rating: number;
  reviews: number;
  sold: number;
  description: string;
  features: string[];
  image: string;
  badge?: string;
  inStock: boolean;
  shipsFrom: "US" | "CN";
  deliveryDays: string;
  supplier: string;
}

export interface Collection {
  id: string;
  name: string;
  description: string;
  image: string;
  productCount: number;
}

export const collections: Collection[] = [
  {
    id: "best-sellers",
    name: "Best Sellers",
    description: "Our most popular smart home devices, trusted by thousands of homeowners",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    productCount: 12,
  },
  {
    id: "smart-hub",
    name: "Smart Control",
    description: "Central hubs and controllers for a fully connected home",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    productCount: 6,
  },
  {
    id: "security",
    name: "Security & Cameras",
    description: "Keep your home safe with AI-powered cameras and smart sensors",
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80",
    productCount: 6,
  },
  {
    id: "climate",
    name: "Climate & Energy",
    description: "Smart thermostats and energy management for every home",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
    productCount: 5,
  },
  {
    id: "lighting",
    name: "Smart Lighting",
    description: "Intelligent lighting that adapts to your lifestyle",
    image: "https://images.unsplash.com/photo-1565014781890-e6d40e4d5af8?w=800&q=80",
    productCount: 6,
  },
  {
    id: "entertainment",
    name: "Entertainment",
    description: "Smart speakers, displays, and audio for every room",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80",
    productCount: 5,
  },
  {
    id: "automation",
    name: "Home Automation",
    description: "Robot vacuums, smart locks, and automation essentials",
    image: "https://images.unsplash.com/photo-1563906267088-b029e7101114?w=800&q=80",
    productCount: 8,
  },
];

export const products: Product[] = [
  // ── Smart Control / Hubs ────────────────────────────────────────────
  {
    id: "1",
    slug: "nexhub-pro-3",
    name: "NexHub Pro 3",
    price: 299,
    originalPrice: 399,
    category: "Smart Control",
    collection: "smart-hub",
    rating: 4.9,
    reviews: 3241,
    sold: 12800,
    description:
      "The NexHub Pro 3 is the central brain of your smart home. Control thousands of compatible devices from a single app, create complex automations, and enjoy seamless voice control.",
    features: [
      "Controls 10,000+ compatible devices",
      "Matter & Thread protocol support",
      "Built-in Zigbee, Z-Wave, Wi-Fi, Bluetooth 5.3",
      "Local processing for instant response",
      "Works with Alexa, Google, Apple HomeKit",
      "8-core processor, 4GB RAM",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "2",
    slug: "nexhub-mini",
    name: "NexHub Mini",
    price: 149,
    originalPrice: 199,
    category: "Smart Control",
    collection: "smart-hub",
    rating: 4.7,
    reviews: 1876,
    sold: 8400,
    description:
      "Compact smart home hub with full Matter compatibility and lightning-fast local response. Perfect for apartments or as a secondary hub.",
    features: [
      "Compact design, powerful performance",
      "Wi-Fi 6E, Bluetooth 5.2",
      "Matter & Thread certified",
      "Works with 5,000+ devices",
      "Voice assistant ready",
      "30-day standby battery backup",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "3",
    slug: "nexremote-pro",
    name: "NexRemote Pro",
    price: 89,
    originalPrice: 119,
    category: "Smart Control",
    collection: "smart-hub",
    rating: 4.6,
    reviews: 892,
    sold: 4200,
    description:
      "Universal smart remote with touchscreen display. Control your entire smart home without picking up your phone.",
    features: [
      "3.5\" color touchscreen",
      "Gesture control support",
      "Rechargeable battery (7-day life)",
      "Universal IR blaster",
      "Works with NexHub and standalone",
      "Customizable scenes and shortcuts",
    ],
    image: "https://images.unsplash.com/photo-1558618087-7de2c8a0a4e7?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "4",
    slug: "nexbridge-hub",
    name: "NexBridge Protocol Hub",
    price: 69,
    originalPrice: 89,
    category: "Smart Control",
    collection: "smart-hub",
    rating: 4.5,
    reviews: 654,
    sold: 3100,
    description:
      "Bridge older smart home ecosystems with the latest standards. Connect Zigbee, Z-Wave, and legacy devices to your modern setup.",
    features: [
      "Zigbee 3.0 + Z-Wave Plus + Bluetooth",
      "Plug-and-play setup",
      "Extends hub range by 150ft",
      "100+ device capacity",
      "No subscription required",
      "Automatic OTA firmware updates",
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "5",
    slug: "nexwall-controller",
    name: "NexWall Scene Controller",
    price: 129,
    originalPrice: 169,
    category: "Smart Control",
    collection: "smart-hub",
    rating: 4.7,
    reviews: 1122,
    sold: 5600,
    description:
      "Elegant in-wall touchscreen that replaces your light switch with a beautiful 4.3\" scene selector panel.",
    features: [
      "4.3\" flush-mount IPS touchscreen",
      "No neutral wire required",
      "8 programmable scene buttons",
      "Works with all major hubs",
      "Tempered glass face",
      "5-year manufacturer warranty",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    badge: "New",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "6",
    slug: "nexscene-button-pack",
    name: "NexScene Button Pack",
    price: 49,
    originalPrice: 69,
    category: "Smart Control",
    collection: "smart-hub",
    rating: 4.4,
    reviews: 443,
    sold: 2100,
    description:
      "Wireless, battery-free scene control buttons. Stick anywhere and create one-touch automations.",
    features: [
      "Energy harvesting — no batteries ever",
      "3M adhesive + magnetic mount",
      "Range: 150ft through walls",
      "3 buttons per pack",
      "Fully customizable per button",
      "Works with NexHub and others",
    ],
    image: "https://images.unsplash.com/photo-1558618087-7de2c8a0a4e7?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },

  // ── Security & Cameras ──────────────────────────────────────────────
  {
    id: "7",
    slug: "nexcam-4k-outdoor",
    name: "NexCam 4K Outdoor",
    price: 149,
    originalPrice: 199,
    category: "Security",
    collection: "security",
    rating: 4.8,
    reviews: 4521,
    sold: 18700,
    description:
      "Professional-grade 4K outdoor security camera with color night vision, AI detection, and a 110dB built-in spotlight.",
    features: [
      "4K Ultra HD resolution",
      "Full-color night vision up to 30ft",
      "AI person / vehicle / pet detection",
      "Built-in 110dB siren + spotlight",
      "IP67 weatherproof rated",
      "Local + optional cloud storage",
    ],
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
    badge: "Top Rated",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "8",
    slug: "nexcam-indoor-360",
    name: "NexCam Indoor 360°",
    price: 99,
    originalPrice: 139,
    category: "Security",
    collection: "security",
    rating: 4.7,
    reviews: 2876,
    sold: 11200,
    description:
      "Full 360° indoor camera with motorized pan/tilt, two-way audio, and crystal-clear 2K resolution.",
    features: [
      "2K QHD resolution",
      "360° pan, 90° tilt (motorized)",
      "Two-way audio with noise cancellation",
      "Auto motion tracking",
      "IR night vision in complete darkness",
      "Privacy shutter included",
    ],
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "9",
    slug: "nexdoor-pro",
    name: "NexDoor Pro Video Doorbell",
    price: 179,
    originalPrice: 249,
    category: "Security",
    collection: "security",
    rating: 4.8,
    reviews: 3102,
    sold: 13500,
    description:
      "The smartest video doorbell with 1080p HD, instant mobile alerts, and built-in package detection AI.",
    features: [
      "1080p HD with 180° wide-angle lens",
      "Package detection AI",
      "Instant push notifications",
      "Works with existing doorbell wiring",
      "Local + cloud storage",
      "Pre-buffer records before motion",
    ],
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "10",
    slug: "nexsense-motion-pro",
    name: "NexSense Motion Pro",
    price: 49,
    originalPrice: 69,
    category: "Security",
    collection: "security",
    rating: 4.6,
    reviews: 1543,
    sold: 7800,
    description:
      "Ultra-sensitive motion sensor with pet immunity and multi-zone detection. Triggers automations in under 500ms.",
    features: [
      "100° wide-angle detection zone",
      "Pet immunity up to 50lbs",
      "Response time under 500ms",
      "Battery life: 3+ years",
      "Built-in temperature & humidity sensor",
      "Wireless — no wiring required",
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "11",
    slug: "nexsensor-door-window",
    name: "NexSensor Door & Window 3-Pack",
    price: 39,
    originalPrice: 59,
    category: "Security",
    collection: "security",
    rating: 4.5,
    reviews: 987,
    sold: 5100,
    description:
      "Compact door and window sensors that trigger instant alerts and automations when opened or closed.",
    features: [
      "3-sensor pack",
      "Wireless, 2-year battery life",
      "Instant breach alerts via app",
      "Works with all major hubs",
      "Ultra-thin — invisible when closed",
      "Built-in temperature sensor",
    ],
    image: "https://images.unsplash.com/photo-1558618087-7de2c8a0a4e7?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "12",
    slug: "nexguard-4-camera-kit",
    name: "NexGuard 4-Camera Security Kit",
    price: 449,
    originalPrice: 599,
    category: "Security",
    collection: "security",
    rating: 4.9,
    reviews: 2341,
    sold: 9800,
    description:
      "Complete home security system with 4 outdoor cameras, NVR recorder, and 2TB of local storage. No subscription ever.",
    features: [
      "4× NexCam 4K Outdoor cameras",
      "8-channel NVR with 2TB HDD",
      "30 days continuous recording",
      "Motion-triggered smart alerts",
      "Remote viewing from anywhere",
      "Professional installation guide included",
    ],
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&q=80",
    badge: "Bundle",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "5–7",
    supplier: "NexTech Industries",
  },

  // ── Climate & Energy ────────────────────────────────────────────────
  {
    id: "13",
    slug: "nextherm",
    name: "NexTherm Smart Thermostat",
    price: 199,
    originalPrice: 279,
    category: "Climate",
    collection: "climate",
    rating: 4.9,
    reviews: 5621,
    sold: 24300,
    description:
      "The NexTherm learns your schedule and preferences automatically, optimizing your home's temperature for comfort and energy savings.",
    features: [
      "Auto-scheduling AI learning",
      "Saves up to 23% on energy bills",
      "Remote control via app",
      "Compatible with 99% of HVAC systems",
      "Beautiful AMOLED color display",
      "Monthly energy usage reports",
    ],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "14",
    slug: "nextherm-lite",
    name: "NexTherm Lite",
    price: 129,
    originalPrice: 179,
    category: "Climate",
    collection: "climate",
    rating: 4.6,
    reviews: 2311,
    sold: 10200,
    description:
      "Affordable smart thermostat with all the essential features. Easy DIY installation in under 30 minutes.",
    features: [
      "Wi-Fi connected",
      "Weekly schedule programming",
      "Compatible with most HVAC systems",
      "Bright LED display",
      "Geofencing auto-away",
      "Works with Alexa & Google",
    ],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "15",
    slug: "nexair-pro-monitor",
    name: "NexAir Pro Monitor",
    price: 129,
    originalPrice: 179,
    category: "Climate",
    collection: "climate",
    rating: 4.7,
    reviews: 1432,
    sold: 6700,
    description:
      "Comprehensive indoor air quality monitor tracking CO2, VOCs, humidity, temperature, and PM2.5 in real-time.",
    features: [
      "Monitors CO2, PM2.5, VOC, Temp, Humidity",
      "Color-coded air quality index",
      "Historical data tracking (30 days)",
      "Triggers ventilation automations",
      "OLED display",
      "7-day battery or USB-C powered",
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    badge: "New",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "16",
    slug: "nexenergy-monitor",
    name: "NexEnergy Whole-Home Monitor",
    price: 99,
    originalPrice: 149,
    category: "Climate",
    collection: "climate",
    rating: 4.5,
    reviews: 876,
    sold: 4100,
    description:
      "Real-time electricity monitoring for your entire home. Identify energy hogs and cut your utility bill.",
    features: [
      "Real-time per-device usage monitoring",
      "Monthly bill prediction",
      "Solar production monitoring support",
      "Works with 200A panels",
      "App-based alerts for anomalies",
      "No electrician needed — DIY install",
    ],
    image: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "17",
    slug: "nexvent-fan-controller",
    name: "NexVent Smart Fan Controller",
    price: 79,
    originalPrice: 109,
    category: "Climate",
    collection: "climate",
    rating: 4.4,
    reviews: 554,
    sold: 2800,
    description:
      "Turn any ceiling fan into a smart fan. Schedule, set speeds, and automate without replacing the fan.",
    features: [
      "Works with any ceiling fan",
      "5 speed settings + reverse",
      "Schedule-based automation",
      "Works with existing wall switch",
      "No hub required",
      "Alexa & Google compatible",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },

  // ── Smart Lighting ──────────────────────────────────────────────────
  {
    id: "18",
    slug: "nexbulb-color-4pack",
    name: "NexBulb Color A19 4-Pack",
    price: 59,
    originalPrice: 89,
    category: "Lighting",
    collection: "lighting",
    rating: 4.8,
    reviews: 6732,
    sold: 31200,
    description:
      "16 million colors and tunable white light in a standard A19 bulb. Transform any room with voice or app control.",
    features: [
      "16 million color options",
      "2700K–6500K tunable white",
      "800 lumen output per bulb",
      "25,000 hour lifespan",
      "No hub required (direct Wi-Fi)",
      "Works with Alexa, Google, HomeKit",
    ],
    image: "https://images.unsplash.com/photo-1565014781890-e6d40e4d5af8?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "19",
    slug: "nexbulb-white-6pack",
    name: "NexBulb White 6-Pack",
    price: 49,
    originalPrice: 79,
    category: "Lighting",
    collection: "lighting",
    rating: 4.6,
    reviews: 3211,
    sold: 15400,
    description:
      "Tunable white smart bulbs for every room. Shift from warm to daylight to match your mood or task.",
    features: [
      "2700K–6500K color temperature range",
      "800 lumen, 6-bulb pack",
      "App + voice control",
      "Schedule & automation support",
      "Dims to 1% without flicker",
      "Energy Star certified",
    ],
    image: "https://images.unsplash.com/photo-1565014781890-e6d40e4d5af8?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "20",
    slug: "nexglow-strip-16ft",
    name: "NexGlow LED Strip 16ft",
    price: 79,
    originalPrice: 119,
    category: "Lighting",
    collection: "lighting",
    rating: 4.7,
    reviews: 4532,
    sold: 21800,
    description:
      "Dreamcolor RGBIC LED strip with individually addressable segments. Create stunning effects behind your TV or under cabinets.",
    features: [
      "Individually addressable RGBIC",
      "16ft flexible strip",
      "Music sync mode",
      "Cuttable every 4 inches",
      "Self-adhesive backing",
      "App + voice control",
    ],
    image: "https://images.unsplash.com/photo-1565014781890-e6d40e4d5af8?w=600&q=80",
    badge: "Most Popular",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "21",
    slug: "nexglow-strip-32ft",
    name: "NexGlow LED Strip 32ft Pro",
    price: 129,
    originalPrice: 189,
    category: "Lighting",
    collection: "lighting",
    rating: 4.7,
    reviews: 2187,
    sold: 10400,
    description:
      "Extra-long 32ft dreamcolor LED strip for large spaces, staircases, or full room accent lighting.",
    features: [
      "32ft addressable RGBIC",
      "IP44 rated for slight moisture",
      "Music sync, preset scene modes",
      "60 LEDs/meter density",
      "2-year warranty",
      "Works with NexHub or standalone",
    ],
    image: "https://images.unsplash.com/photo-1565014781890-e6d40e4d5af8?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "22",
    slug: "nexswitch-pro-dimmer",
    name: "NexSwitch Pro Dimmer",
    price: 49,
    originalPrice: 69,
    category: "Lighting",
    collection: "lighting",
    rating: 4.6,
    reviews: 1876,
    sold: 9200,
    description:
      "In-wall smart dimmer switch. Works with any dimmable bulb and requires no hub for standalone Wi-Fi operation.",
    features: [
      "Works with any dimmable bulb",
      "No neutral wire required",
      "Physical + touch + app control",
      "30-minute DIY installation",
      "Energy monitoring built-in",
      "Works with Alexa, Google, HomeKit",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "23",
    slug: "nexoutdoor-string-lights",
    name: "NexOutdoor Smart String Lights",
    price: 69,
    originalPrice: 99,
    category: "Lighting",
    collection: "lighting",
    rating: 4.5,
    reviews: 1231,
    sold: 5700,
    description:
      "Weatherproof outdoor smart string lights. Perfect for patios, pergolas, and garden spaces.",
    features: [
      "48ft weatherproof string",
      "15 Edison-style G40 bulbs",
      "RGBW color-capable",
      "IP65 waterproof rated",
      "App + voice control",
      "Commercial-grade shatterproof bulbs",
    ],
    image: "https://images.unsplash.com/photo-1565014781890-e6d40e4d5af8?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },

  // ── Entertainment ───────────────────────────────────────────────────
  {
    id: "24",
    slug: "nexsound-pro-speaker",
    name: "NexSound Pro Speaker",
    price: 199,
    originalPrice: 279,
    category: "Entertainment",
    collection: "entertainment",
    rating: 4.8,
    reviews: 3421,
    sold: 15600,
    description:
      "Premium 360° smart speaker with room-filling sound, built-in voice assistant, and multi-room audio sync.",
    features: [
      "360° omnidirectional audio",
      "40W total output, dual tweeter",
      "Multi-room sync (stereo pairable)",
      "Built-in Alexa & Google Assistant",
      "Adaptive EQ auto-tuning",
      "Lossless audio streaming",
    ],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    badge: "Editor's Choice",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "25",
    slug: "nexsound-mini-speaker",
    name: "NexSound Mini",
    price: 99,
    originalPrice: 139,
    category: "Entertainment",
    collection: "entertainment",
    rating: 4.6,
    reviews: 1876,
    sold: 8900,
    description:
      "Compact smart speaker that punches well above its size. Perfect for bedrooms, kitchens, and offices.",
    features: [
      "20W with passive radiator bass",
      "Stereo pairable",
      "Voice + app + touch control",
      "Wi-Fi + Bluetooth 5.0",
      "Works with NexHub",
      "LED ring with customizable color",
    ],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "26",
    slug: "nexdisplay-10",
    name: "NexDisplay 10\" Smart Screen",
    price: 299,
    originalPrice: 399,
    category: "Entertainment",
    collection: "entertainment",
    rating: 4.8,
    reviews: 2134,
    sold: 9700,
    description:
      "Smart home control center with a 10\" touchscreen. View cameras, control devices, video call, and stream content.",
    features: [
      "10\" 1080p IPS touchscreen",
      "Built-in 8MP camera",
      "Smart home dashboard view",
      "Video calling & streaming",
      "Wall-mount or countertop stand",
      "Hardware privacy camera shutter",
    ],
    image: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?w=600&q=80",
    badge: "New",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "27",
    slug: "nextvbar-pro-soundbar",
    name: "NexTV Bar Pro Soundbar",
    price: 349,
    originalPrice: 499,
    category: "Entertainment",
    collection: "entertainment",
    rating: 4.7,
    reviews: 1432,
    sold: 6200,
    description:
      "Immersive 5.1ch Dolby Atmos soundbar with wireless subwoofer and multi-room audio integration.",
    features: [
      "Dolby Atmos & DTS:X decoding",
      "240W total output",
      "Wireless subwoofer included",
      "HDMI eARC connection",
      "Integrates as smart home audio output",
      "AI room calibration",
    ],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "5–7",
    supplier: "NexTech Industries",
  },
  {
    id: "28",
    slug: "nexaudio-wireless-sub",
    name: "NexAudio Wireless Subwoofer",
    price: 249,
    originalPrice: 349,
    category: "Entertainment",
    collection: "entertainment",
    rating: 4.5,
    reviews: 876,
    sold: 3800,
    description:
      "Wireless 8\" subwoofer that pairs with any NexSound speaker for deep, room-shaking bass.",
    features: [
      "8\" driver, 100W Class D amplifier",
      "Wireless link to NexSound speakers",
      "Adjustable crossover & volume",
      "Auto-on / auto-off with speakers",
      "App-based EQ control",
      "Works up to 30ft from speakers",
    ],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "5–7",
    supplier: "NexTech Industries",
  },

  // ── Home Automation ─────────────────────────────────────────────────
  {
    id: "29",
    slug: "nexclean-pro-robot",
    name: "NexClean Pro Vacuum & Mop",
    price: 499,
    originalPrice: 699,
    category: "Automation",
    collection: "automation",
    rating: 4.9,
    reviews: 4321,
    sold: 18900,
    description:
      "AI-powered robot vacuum and mop with LiDAR navigation, self-emptying base, and 6000Pa suction power.",
    features: [
      "LiDAR precision room mapping",
      "6000Pa max suction",
      "Simultaneous vacuum + mop",
      "60-day self-emptying base",
      "Obstacle avoidance AI",
      "Multi-room zone cleaning & no-go zones",
    ],
    image: "https://images.unsplash.com/photo-1563906267088-b029e7101114?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "30",
    slug: "nexclean-air-purifier",
    name: "NexClean Air Purifier Pro",
    price: 299,
    originalPrice: 399,
    category: "Automation",
    collection: "automation",
    rating: 4.7,
    reviews: 2211,
    sold: 9800,
    description:
      "Smart air purifier with 3-stage HEPA filtration, real-time air quality display, and intelligent auto mode.",
    features: [
      "True HEPA H13 filter",
      "Covers up to 500 sq ft",
      "Real-time air quality sensor display",
      "Auto mode adjusts to air quality",
      "Ultra-quiet: 22dB in night mode",
      "Filter replacement reminders via app",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "31",
    slug: "nexbot-floor-scrubber",
    name: "NexBot Floor Scrubber",
    price: 199,
    originalPrice: 279,
    category: "Automation",
    collection: "automation",
    rating: 4.5,
    reviews: 987,
    sold: 4500,
    description:
      "Automatic floor scrubber that washes, scrubs, and dries hard floors without human intervention.",
    features: [
      "Auto-dispense cleaning solution",
      "Self-cleaning dock",
      "Safe for hardwood, tile, vinyl",
      "90 minutes per charge",
      "App scheduling + voice control",
      "Works with NexHub",
    ],
    image: "https://images.unsplash.com/photo-1563906267088-b029e7101114?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "32",
    slug: "nexroutine-automation-hub",
    name: "NexRoutine Automation Hub",
    price: 89,
    originalPrice: 129,
    category: "Automation",
    collection: "automation",
    rating: 4.6,
    reviews: 1123,
    sold: 5400,
    description:
      "Dedicated local automation processor. Run complex if-this-then-that routines without cloud dependency.",
    features: [
      "100% local processing — no cloud",
      "Unlimited automation rules",
      "Webhook & REST API integration",
      "Home Assistant compatible",
      "4-hour battery backup",
      "Open API for developers",
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    badge: "New",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "33",
    slug: "nexflow-smart-sprinkler",
    name: "NexFlow Smart Sprinkler",
    price: 149,
    originalPrice: 199,
    category: "Automation",
    collection: "automation",
    rating: 4.5,
    reviews: 765,
    sold: 3600,
    description:
      "Weather-adaptive sprinkler controller that waters only when needed, saving up to 50% water usage.",
    features: [
      "8-zone control",
      "Weather-based automatic skip",
      "Works with most sprinkler systems",
      "Soil moisture sensor integration",
      "Flow sensor support",
      "EPA WaterSense certified",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    shipsFrom: "CN",
    deliveryDays: "7–14",
    supplier: "SmartTech Global",
  },
  {
    id: "34",
    slug: "nexlock-pro-smart-lock",
    name: "NexLock Pro Smart Lock",
    price: 229,
    originalPrice: 299,
    category: "Automation",
    collection: "automation",
    rating: 4.8,
    reviews: 2876,
    sold: 12400,
    description:
      "Keyless smart door lock with fingerprint, PIN, app, and physical key access. Auto-lock and tamper alerts.",
    features: [
      "Fingerprint + PIN + app + key access",
      "100 unique user codes",
      "Auto-lock + auto-unlock by geofence",
      "Tamper & low battery alerts",
      "Installs on existing deadbolt",
      "Z-Wave + Wi-Fi dual radio",
    ],
    image: "https://images.unsplash.com/photo-1558618087-7de2c8a0a4e7?w=600&q=80",
    badge: "Best Seller",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "35",
    slug: "nexgarage-controller",
    name: "NexGarage Smart Controller",
    price: 89,
    originalPrice: 129,
    category: "Automation",
    collection: "automation",
    rating: 4.6,
    reviews: 1432,
    sold: 6700,
    description:
      "Make any garage door opener smart. Check status, open/close remotely, and set delivery access windows.",
    features: [
      "Works with 95% of garage door openers",
      "Remote open/close from anywhere",
      "Tilt sensor for status detection",
      "Auto-close timer",
      "Delivery access scheduling",
      "Works with Alexa, Google, HomeKit",
    ],
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
  {
    id: "36",
    slug: "nexplug-4pack",
    name: "NexPlug Smart Plug 4-Pack",
    price: 49,
    originalPrice: 79,
    category: "Automation",
    collection: "automation",
    rating: 4.5,
    reviews: 4231,
    sold: 19800,
    description:
      "Make any appliance smart. Schedule, automate, and monitor energy use of any plug-in device.",
    features: [
      "4-pack value",
      "Individual energy monitoring per plug",
      "Schedule, countdown, automation",
      "Compact — won't block the second outlet",
      "Works with Alexa, Google, HomeKit",
      "No hub required (direct Wi-Fi)",
    ],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    shipsFrom: "US",
    deliveryDays: "3–5",
    supplier: "NexTech Industries",
  },
];

export function getBestSellers(n: number): Product[] {
  return [...products].sort((a, b) => b.sold - a.sold).slice(0, n);
}

export function getCollectionById(id: string): Collection | undefined {
  return collections.find((c) => c.id === id);
}

export function getProductsByCollection(id: string): Product[] {
  if (id === "best-sellers") return getBestSellers(12);
  return products.filter((p) => p.collection === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, n: number): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.collection === product.collection)
    .slice(0, n);
}
