// Regenerates src/game/data/map.ts from the Java resource, so the desktop game and the
// browser game always play the same world.
//
//   node scripts/generate-map.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, "game/src/main/resources/maps/ashvale.map");
const target = resolve(root, "src/game/data/map.ts");

const map = readFileSync(source, "utf8").trimEnd();
if (map.includes("`") || map.includes("${")) {
  throw new Error("The map file contains characters that cannot go in a template literal");
}

writeFileSync(
  target,
  `// Generated by scripts/generate-map.mjs from game/src/main/resources/maps/ashvale.map.\n` +
    `// Edit the .map file and re-run the script rather than editing this one.\n\n` +
    `export const ASHVALE_MAP = \`\n${map}\n\`;\n`,
);

console.log(`Wrote ${target} (${map.length} characters)`);
